version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://user:password@mongodb:27017/k8s_interview

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data: